import process from "process";
import esbuild from "esbuild";
import builtins from "builtin-modules";

const banner = 
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to check source code, please visit https://github.com/Doggy-Footprint/Obsidian-keyword-suggest
*/
`;

const prod = (process.argv.some(v === "production"));

const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: ["obsidian_srcs/main.ts", "obsidian_srcs/style.css"],
    bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
